name: FS
description: Fortec Scanner
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  path_provider: ^2.1.4
  firebase_data_connect: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "/home/line/Documentos/FS/app_fs_new/lib/assets/icon/app_icon.png"

flutter:
  uses-material-design: true
