// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiljYaq9Dph6qcKgWW06N5us2MB1ZD2E',
    appId: '1:522028208564:web:db6c6114d317f1abe262e1',
    messagingSenderId: '522028208564',
    projectId: 'app-projeto-e7993',
    authDomain: 'app-projeto-e7993.firebaseapp.com',
    databaseURL: 'https://app-projeto-e7993-default-rtdb.firebaseio.com',
    storageBucket: 'app-projeto-e7993.firebasestorage.app',
    measurementId: 'G-DPXSTMCQZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVC0hETUA8E7ds_autu5_Li_H8JrFNc0Y',
    appId: '1:522028208564:android:6643d806651f7dcbe262e1',
    messagingSenderId: '522028208564',
    projectId: 'app-projeto-e7993',
    databaseURL: 'https://app-projeto-e7993-default-rtdb.firebaseio.com',
    storageBucket: 'app-projeto-e7993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzu0xWS1FON6o23xKCbRlTR1677NyzJCU',
    appId: '1:522028208564:ios:fc00c5552cb2f859e262e1',
    messagingSenderId: '522028208564',
    projectId: 'app-projeto-e7993',
    databaseURL: 'https://app-projeto-e7993-default-rtdb.firebaseio.com',
    storageBucket: 'app-projeto-e7993.firebasestorage.app',
    iosBundleId: 'com.example.placas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzu0xWS1FON6o23xKCbRlTR1677NyzJCU',
    appId: '1:522028208564:ios:fc00c5552cb2f859e262e1',
    messagingSenderId: '522028208564',
    projectId: 'app-projeto-e7993',
    databaseURL: 'https://app-projeto-e7993-default-rtdb.firebaseio.com',
    storageBucket: 'app-projeto-e7993.firebasestorage.app',
    iosBundleId: 'com.example.placas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQiljYaq9Dph6qcKgWW06N5us2MB1ZD2E',
    appId: '1:522028208564:web:92e14c35b5d944b7e262e1',
    messagingSenderId: '522028208564',
    projectId: 'app-projeto-e7993',
    authDomain: 'app-projeto-e7993.firebaseapp.com',
    databaseURL: 'https://app-projeto-e7993-default-rtdb.firebaseio.com',
    storageBucket: 'app-projeto-e7993.firebasestorage.app',
    measurementId: 'G-TMLMHNE9YY',
  );
}